version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
  notification-service:
    build: ./notification-service
    ports:
      - "3002:3002"
  timer-app:
    build: ./timer-app
    ports:
      - "3003:3003"
  metronome-app:
    build: ./metronome-app
    ports:
      - "3004:3004"
